### ISSUE TITLE
Models not loading

### ISSUE THREAD

**Issue by waigwamacha** [garciaml/BrainQCNet#2]
Hi,

We wanted to try out this app in our lab. However, we realized that the links to the saved models for the CPU and GPU are missing. Please let me know where we can find them, or update the links.

Thanks so much!

**Comment by garciaml** [comment]
Hi,
Thank you very much for raising this issue, and many apologies for the inconvenience.
I just updated the links!
I remain available for any help you may need to run the app.
Melanie

**Comment by garciaml** [comment]
Links updated!

**Comment by waigwamacha** [comment]
Thanks so much! I was able to download the models

Also, I noticed that, although you define the python for use in the docker image, the image actually still expects to use the local python on venv/bin/python, rather than the python installed in the docker image. The * #!/usr/bin/env/python3* in the run.py file actually points to the python in the local computer rather than the image. So when i run the app I get the error below:

The error we get is **FATAL: stat /home/user/venv/bin/python3: no such file or directory** 

I suspect the problem is in the run.py file as mentioned. If you can test it on your end and update on a solution, that would be very helpful. Many thanks :)

**Comment by garciaml** [comment]
Ok thanks for reporting this new issue! I will check it and get back to you as soon as I have fixed this.

**Comment by garciaml** [comment]
Hi, have you found where the issue came from? 
Everything works well on my end.
